### ISSUE TITLE
Peer to peer code review 8/7/2022

### ISSUE THREAD

**Issue by DiegoMero** [williamscch/to-do-list#3]

**Comment by DiegoMero** [comment]
**Highlights**

- Good work making the checkbox function, everything is working well.

**Comment by jaferIdrees** [comment]
Hi David,
Great work so far, 
Highlights 

- Created exactly the required skeleton. 💯 
- No linters errors 💯 
- Basic functions of editing and adding new tasks are working very well 💯 

I have the below suggestions for you:
-make better font and text formatting 👍 
-Utilize CSS to apply the text-decoration for the completed tasks. 🍒 

Happy coding,

**Comment by nimplay** [comment]
Excellent job!

- [x] Kindly, you need to rename the Js files with the right names

**Comment by williamscch** [comment]
Thank you so much for the suggestions guys, I just refactored my code and I solve all those problems.
