### ISSUE TITLE
Peer-to-peer code review 12/07/2022

### ISSUE THREAD

**Issue by lucas-crodrigues** [williamscch/to-do-list#5]
First of all, congratulations on your code, the app looks great, and there are no known bugs 🔥 💯 

Here are a few suggestions to improve on it:
https://github.com/wdavidcch/to-do-list/blob/d0a04d0ef2104c40ff87edf019b4b0077f147171/src/index.js#L29-L39

- [x] Here if you put the input in a form with a button, both with "type = 'submit' " you can just have an event listener for "submit", it'll grab both click and keypress, the way it is right now you don't need the preventDefault since it's not a form

**Comment by jaferIdrees** [comment]
- [ ] For the page functionality I noticed that when you change any task completed status by checking the checkbox, it doesn't update the value in the localStorage hence if you refresh the page you lose these changes, I believe you need to import the checkbox event listener from the module and use it in index.js. 👍 
### JavaScript best practices
- [x] it's recommended to keep all variables declarations on the top of your code. 🍒
